---
commodities: ["postgres", "elasticsearch5", "rabbitmq", "db2_community"]
# Optional
expensive_startup:
  - compose_service: name-of-service-from-compose-fragment
    healthcheck_cmd: docker-or-a-shell-command-that-returns-0-exit-code-if-healthy
    # Optional
    wait_until_healthy:
      - compose_service: db2_community
        healthcheck_cmd: docker
perform_alembic_migration: true
