version: "3.7"
services:
  # Back-compat: So apps compose files dont need to care if its logstash or not, call this container logstash as well
  logstash:
    container_name: logstash
    build: ../scripts/docker/logging
    volumes:
      - ../logs:/log-dir
    ports:
      - "25826:25826"
    restart: on-failure
