version: '3'
services:
  elasticsearch5:
    container_name: elasticsearch5
    build: ../scripts/docker/elasticsearch5
    ports:
      - "9202:9200"
      - "9302:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    restart: on-failure
    resources:
      limits:
        memory: 2048M
